replicaCount: 1

image:
  repository: docker.io/yourdockeruser/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  hosts: []
  tls: []

